export const VERSUS_FETCH = 'MATCHES_FETCH';
export const VERSUS_FETCHING = 'MATCHES_FETCHING';
export const VERSUS_FETCHED = 'MATCHES_FETCHED';
export const VERSUS_ERROR_FETCH = 'MATCHES_ERROR_FETCH';
export const UPDATE_SELECTED_SEASON = 'UPDATE_SELECTED_SEASON';
