export const PLAYERS_FETCH = 'PLAYERS_FETCH';
export const PLAYERS_FETCHING = 'PLAYERS_FETCHING';
export const PLAYERS_FETCHED = 'PLAYERS_FETCHED';
export const PLAYERS_ERROR_FETCH = 'PLAYERS_ERROR_FETCH';

