export const MATCH_DETAILS_FETCH = 'MATCH_DETAILS_FETCH';
export const MATCH_DETAILS_FETCHING = 'MATCH_DETAILS_FETCHING';
export const MATCH_DETAILS_FETCHED = 'MATCH_DETAILS_FETCHED';
export const MATCH_DETAILS_ERROR_FETCH = 'MATCH_DETAILS_ERROR_FETCH';