export const SEARCH_FETCH = 'SEARCH_FETCH';
export const SEARCH_FETCHING = 'SEARCH_FETCHING';
export const SEARCH_FETCHED = 'SEARCH_FETCHED';
export const SEARCH_ERROR_FETCH = 'SEARCH_ERROR_FETCH';

export const TUPLES_FETCH = 'TUPLES_FETCH';
export const TUPLES_FETCHING = 'TUPLES_FETCHING';
export const TUPLES_FETCHED = 'TUPLES_FETCHED';
export const TUPLES_ERROR_FETCH = 'TUPLES_ERROR_FETCH';