export const TEAM_DETAILS_FETCH = 'TEAM_FETCH';
export const TEAM_DETAILS_FETCHING = 'TEAM_FETCHING';
export const TEAM_DETAILS_FETCHED = 'TEAM_FETCHED';
export const TEAM_DETAILS_ERROR_FETCH = 'TEAM_ERROR_FETCH';