export const MATCHES_FETCH = 'MATCHES_FETCH';
export const MATCHES_FETCHING = 'MATCHES_FETCHING';
export const MATCHES_FETCHED = 'MATCHES_FETCHED';
export const MATCHES_ERROR_FETCH = 'MATCHES_ERROR_FETCH';

