export const PLAYER_DETAILS_FETCH = 'PLAYER_DETAILS_FETCH';
export const PLAYER_DETAILS_FETCHING = 'PLAYER_DETAILS_FETCHING';
export const PLAYER_DETAILS_FETCHED = 'PLAYER_DETAILS_FETCHED';
export const PLAYER_DETAILS_ERROR_FETCH = 'PLAYER_DETAILS_ERROR_FETCH';